version: "3.9"

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "5000:5000"           
    volumes:
      - .:/app              
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"          
    depends_on:
      - proxy                
    restart: unless-stopped
